"""Initial ARIA database schema

Revision ID: 84d02206c812
Revises: 
Create Date: 2025-10-30 16:34:48.577863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '84d02206c812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_data', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_occurrence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_patterns_pattern_type'), 'interaction_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_interaction_patterns_user_id'), 'interaction_patterns', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlock_count', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('context_key', sa.String(length=255), nullable=False),
    sa.Column('context_value', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_context_context_key'), 'user_context', ['context_key'], unique=False)
    op.create_index(op.f('ix_user_context_context_type'), 'user_context', ['context_type'], unique=False)
    op.create_index(op.f('ix_user_context_importance_score'), 'user_context', ['importance_score'], unique=False)
    op.create_index(op.f('ix_user_context_user_id'), 'user_context', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_type', sa.String(length=50), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('aria_response', sa.Text(), nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('response_generated', sa.Boolean(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_session_id'), 'system_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_events_user_id'), 'system_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_events_user_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_session_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_user_context_user_id'), table_name='user_context')
    op.drop_index(op.f('ix_user_context_importance_score'), table_name='user_context')
    op.drop_index(op.f('ix_user_context_context_type'), table_name='user_context')
    op.drop_index(op.f('ix_user_context_context_key'), table_name='user_context')
    op.drop_table('user_context')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_interaction_patterns_user_id'), table_name='interaction_patterns')
    op.drop_index(op.f('ix_interaction_patterns_pattern_type'), table_name='interaction_patterns')
    op.drop_table('interaction_patterns')
    # ### end Alembic commands ###
