"""Initial ARIA database schema with Bible RAG tables

Revision ID: e2bbedff860b
Revises: 
Create Date: 2025-11-03 14:06:31.518595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bbedff860b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('translation', sa.String(length=10), nullable=True),
    sa.Column('results_data', sa.JSON(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('sources_count', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bible_queries_query_type'), 'bible_queries', ['query_type'], unique=False)
    op.create_index(op.f('ix_bible_queries_timestamp'), 'bible_queries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_bible_queries_translation'), 'bible_queries', ['translation'], unique=False)
    op.create_index(op.f('ix_bible_queries_user_id'), 'bible_queries', ['user_id'], unique=False)
    op.create_table('bible_study_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('verses_studied', sa.JSON(), nullable=True),
    sa.Column('queries_count', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bible_study_sessions_session_type'), 'bible_study_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_bible_study_sessions_topic'), 'bible_study_sessions', ['topic'], unique=False)
    op.create_index(op.f('ix_bible_study_sessions_user_id'), 'bible_study_sessions', ['user_id'], unique=False)
    op.create_table('interaction_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('pattern_data', sa.JSON(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_occurrence', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_patterns_pattern_type'), 'interaction_patterns', ['pattern_type'], unique=False)
    op.create_index(op.f('ix_interaction_patterns_user_id'), 'interaction_patterns', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlock_count', sa.Integer(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_bible_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('preferred_translation', sa.String(length=10), nullable=True),
    sa.Column('favorite_verses', sa.JSON(), nullable=True),
    sa.Column('reading_plan', sa.JSON(), nullable=True),
    sa.Column('reading_progress', sa.JSON(), nullable=True),
    sa.Column('study_topics', sa.JSON(), nullable=True),
    sa.Column('daily_verse_enabled', sa.Boolean(), nullable=True),
    sa.Column('commentary_enabled', sa.Boolean(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bible_preferences_user_id'), 'user_bible_preferences', ['user_id'], unique=False)
    op.create_table('user_context',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('context_key', sa.String(length=255), nullable=False),
    sa.Column('context_value', sa.JSON(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_context_context_key'), 'user_context', ['context_key'], unique=False)
    op.create_index(op.f('ix_user_context_context_type'), 'user_context', ['context_type'], unique=False)
    op.create_index(op.f('ix_user_context_importance_score'), 'user_context', ['importance_score'], unique=False)
    op.create_index(op.f('ix_user_context_user_id'), 'user_context', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_type', sa.String(length=50), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('aria_response', sa.Text(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_conversation_type'), 'conversations', ['conversation_type'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversations_timestamp'), 'conversations', ['timestamp'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('response_generated', sa.Boolean(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_events_session_id'), 'system_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_system_events_timestamp'), 'system_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_events_user_id'), 'system_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_events_user_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_timestamp'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_session_id'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_timestamp'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_type'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_user_context_user_id'), table_name='user_context')
    op.drop_index(op.f('ix_user_context_importance_score'), table_name='user_context')
    op.drop_index(op.f('ix_user_context_context_type'), table_name='user_context')
    op.drop_index(op.f('ix_user_context_context_key'), table_name='user_context')
    op.drop_table('user_context')
    op.drop_index(op.f('ix_user_bible_preferences_user_id'), table_name='user_bible_preferences')
    op.drop_table('user_bible_preferences')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_interaction_patterns_user_id'), table_name='interaction_patterns')
    op.drop_index(op.f('ix_interaction_patterns_pattern_type'), table_name='interaction_patterns')
    op.drop_table('interaction_patterns')
    op.drop_index(op.f('ix_bible_study_sessions_user_id'), table_name='bible_study_sessions')
    op.drop_index(op.f('ix_bible_study_sessions_topic'), table_name='bible_study_sessions')
    op.drop_index(op.f('ix_bible_study_sessions_session_type'), table_name='bible_study_sessions')
    op.drop_table('bible_study_sessions')
    op.drop_index(op.f('ix_bible_queries_user_id'), table_name='bible_queries')
    op.drop_index(op.f('ix_bible_queries_translation'), table_name='bible_queries')
    op.drop_index(op.f('ix_bible_queries_timestamp'), table_name='bible_queries')
    op.drop_index(op.f('ix_bible_queries_query_type'), table_name='bible_queries')
    op.drop_table('bible_queries')
    # ### end Alembic commands ###
